spring:
  datasource:
    hikari:
      maximum-pool-size: 15
      connection-timeout: 15000
    reporting:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
    driver-class-name: org.postgresql.Driver

